version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/yousufkalim/node-ts-boilerplate/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  node:
    environment:
      PORT: 5000
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          npm i
          npm run build

workflows:
  my-custom-workflow:
    jobs:
      - node